3rd party: update grub4dos/grubutil

diff --git a/src/grub4dos/configure b/src/grub4dos/configure
--- a/src/grub4dos/configure
+++ b/src/grub4dos/configure
@@ -708,6 +708,7 @@ STAGE2_CFLAGS
 GRUB_CFLAGS
 OBJCOPY
 BIN_LDFLAGS
+BUILD_DIRS
 GRUB_LIBS
 CPP
 GREP
@@ -718,6 +719,8 @@ DISKLESS_SUPPORT_TRUE
 DISKLESS_SUPPORT_FALSE
 GRAPHICS_SUPPORT_TRUE
 GRAPHICS_SUPPORT_FALSE
+GFX_SUPPORT_TRUE
+GFX_SUPPORT_FALSE
 HERCULES_SUPPORT_TRUE
 HERCULES_SUPPORT_FALSE
 SERIAL_SUPPORT_TRUE
@@ -1338,6 +1341,7 @@ Optional Features:
   --disable-xfs           disable SGI XFS support in Stage 2
   --disable-iso9660       disable ISO9660 support in Stage 2
   --disable-pxe           disable PXE support in Stage 2
+  --disable-fb            disable FB support in Stage 2
   --disable-gunzip        disable decompression in Stage 2
   --disable-md5-password  disable MD5 password support in Stage 2
   --disable-packet-retransmission
@@ -1386,6 +1390,7 @@ Optional Features:
   --enable-cs-scan=LIST   probe for CS89x0 base address using LIST
   --enable-diskless       enable diskless support
   --disable-graphics      disable graphics terminal support
+  --disable-gfxmenu       disable gfxmenu support
   --disable-hercules      disable hercules terminal support
   --disable-serial        disable serial terminal support
   --enable-serial-speed-simulation
@@ -4360,11 +4365,14 @@ case "$host_os" in
   mingw32 | cygwin)
     BIN_LDFLAGS="-Wl,-T"'$(top_srcdir)'"/ldscript"
     LDFLAGS="${LDFLAGS} -Wl,-T${srcdir}/ldscript"
+    BUILD_DIRS="netboot stage2 stage1"
     ;;
   *)
     BIN_LDFLAGS="-Wl,-N"
+    BUILD_DIRS="netboot stage2 stage1 lib grub util"
     ;;
 esac
+
 
 
 # Defined in acinclude.m4.
@@ -6218,6 +6226,16 @@ if test x"$enable_pxe" != xno; then
   FSYS_CFLAGS="$FSYS_CFLAGS -DFSYS_PXE=1"
 fi
 
+# Check whether --enable-fb was given.
+if test "${enable_fb+set}" = set; then
+  enableval=$enable_fb;
+fi
+
+
+if test x"$enable_fb" != xno; then
+  FSYS_CFLAGS="$FSYS_CFLAGS -DFSYS_FB=1"
+fi
+
 
 # Check whether --enable-gunzip was given.
 if test "${enable_gunzip+set}" = set; then
@@ -6667,6 +6685,22 @@ else
 fi
 
 
+# Check whether --enable-gfxmenu was given.
+if test "${enable_gfxmenu+set}" = set; then
+  enableval=$enable_gfxmenu;
+fi
+
+
+
+if test "x$enable_gfxmenu" != xno; then
+  GFX_SUPPORT_TRUE=
+  GFX_SUPPORT_FALSE='#'
+else
+  GFX_SUPPORT_TRUE='#'
+  GFX_SUPPORT_FALSE=
+fi
+
+
 # Check whether --enable-hercules was given.
 if test "${enable_hercules+set}" = set; then
   enableval=$enable_hercules;
@@ -6992,6 +7026,13 @@ if test -z "${GRAPHICS_SUPPORT_TRUE}" && test -z "${GRAPHICS_SUPPORT_FALSE}"; th
   { { echo "$as_me:$LINENO: error: conditional \"GRAPHICS_SUPPORT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"GRAPHICS_SUPPORT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${GFX_SUPPORT_TRUE}" && test -z "${GFX_SUPPORT_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"GFX_SUPPORT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"GFX_SUPPORT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -7659,10 +7700,10 @@ STAGE2_CFLAGS!$STAGE2_CFLAGS$ac_delim
 GRUB_CFLAGS!$GRUB_CFLAGS$ac_delim
 OBJCOPY!$OBJCOPY$ac_delim
 BIN_LDFLAGS!$BIN_LDFLAGS$ac_delim
+BUILD_DIRS!$BUILD_DIRS$ac_delim
 GRUB_LIBS!$GRUB_LIBS$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
-EGREP!$EGREP$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -7704,12 +7745,15 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+EGREP!$EGREP$ac_delim
 NETBOOT_SUPPORT_TRUE!$NETBOOT_SUPPORT_TRUE$ac_delim
 NETBOOT_SUPPORT_FALSE!$NETBOOT_SUPPORT_FALSE$ac_delim
 DISKLESS_SUPPORT_TRUE!$DISKLESS_SUPPORT_TRUE$ac_delim
 DISKLESS_SUPPORT_FALSE!$DISKLESS_SUPPORT_FALSE$ac_delim
 GRAPHICS_SUPPORT_TRUE!$GRAPHICS_SUPPORT_TRUE$ac_delim
 GRAPHICS_SUPPORT_FALSE!$GRAPHICS_SUPPORT_FALSE$ac_delim
+GFX_SUPPORT_TRUE!$GFX_SUPPORT_TRUE$ac_delim
+GFX_SUPPORT_FALSE!$GFX_SUPPORT_FALSE$ac_delim
 HERCULES_SUPPORT_TRUE!$HERCULES_SUPPORT_TRUE$ac_delim
 HERCULES_SUPPORT_FALSE!$HERCULES_SUPPORT_FALSE$ac_delim
 SERIAL_SUPPORT_TRUE!$SERIAL_SUPPORT_TRUE$ac_delim
@@ -7727,7 +7771,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 21; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 24; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
